# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'bb.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1200, 870)
        self.horizontalLayoutWidget = QtWidgets.QWidget(Form)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(-1, -1, 1199, 869))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.scrollArea = QtWidgets.QScrollArea(self.horizontalLayoutWidget)
        self.scrollArea.setWidgetResizable(False)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 1199, 869))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.groupBox = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 361, 741))
        self.groupBox.setObjectName("groupBox")
        self.le_go1 = QtWidgets.QLineEdit(self.groupBox)
        self.le_go1.setGeometry(QtCore.QRect(130, 20, 113, 20))
        self.le_go1.setObjectName("le_go1")
        self.pbt_go2 = QtWidgets.QPushButton(self.groupBox)
        self.pbt_go2.setGeometry(QtCore.QRect(260, 50, 75, 23))
        self.pbt_go2.setObjectName("pbt_go2")
        self.le_go20 = QtWidgets.QLineEdit(self.groupBox)
        self.le_go20.setGeometry(QtCore.QRect(130, 670, 113, 20))
        self.le_go20.setObjectName("le_go20")
        self.chb_go15 = QtWidgets.QCheckBox(self.groupBox)
        self.chb_go15.setGeometry(QtCore.QRect(20, 520, 101, 21))
        self.chb_go15.setObjectName("chb_go15")
        self.pbt_go21 = QtWidgets.QPushButton(self.groupBox)
        self.pbt_go21.setGeometry(QtCore.QRect(260, 700, 75, 23))
        self.pbt_go21.setObjectName("pbt_go21")
        self.le_go3 = QtWidgets.QLineEdit(self.groupBox)
        self.le_go3.setGeometry(QtCore.QRect(130, 80, 113, 20))
        self.le_go3.setObjectName("le_go3")
        self.le_go4 = QtWidgets.QLineEdit(self.groupBox)
        self.le_go4.setGeometry(QtCore.QRect(130, 110, 113, 20))
        self.le_go4.setObjectName("le_go4")
        self.le_go16 = QtWidgets.QLineEdit(self.groupBox)
        self.le_go16.setGeometry(QtCore.QRect(130, 550, 113, 20))
        self.le_go16.setObjectName("le_go16")
        self.chb_go7 = QtWidgets.QCheckBox(self.groupBox)
        self.chb_go7.setGeometry(QtCore.QRect(20, 200, 70, 17))
        self.chb_go7.setObjectName("chb_go7")
        self.le_go11 = QtWidgets.QLineEdit(self.groupBox)
        self.le_go11.setGeometry(QtCore.QRect(130, 400, 113, 20))
        self.le_go11.setObjectName("le_go11")
        self.le_go19 = QtWidgets.QLineEdit(self.groupBox)
        self.le_go19.setGeometry(QtCore.QRect(130, 640, 113, 20))
        self.le_go19.setObjectName("le_go19")
        self.chb_go4 = QtWidgets.QCheckBox(self.groupBox)
        self.chb_go4.setGeometry(QtCore.QRect(20, 110, 70, 17))
        self.chb_go4.setObjectName("chb_go4")
        self.chb_go11 = QtWidgets.QCheckBox(self.groupBox)
        self.chb_go11.setGeometry(QtCore.QRect(20, 400, 70, 17))
        self.chb_go11.setObjectName("chb_go11")
        self.pbt_go5 = QtWidgets.QPushButton(self.groupBox)
        self.pbt_go5.setGeometry(QtCore.QRect(260, 140, 75, 23))
        self.pbt_go5.setObjectName("pbt_go5")
        self.chb_go14 = QtWidgets.QCheckBox(self.groupBox)
        self.chb_go14.setGeometry(QtCore.QRect(20, 490, 70, 17))
        self.chb_go14.setObjectName("chb_go14")
        self.pbt_go13 = QtWidgets.QPushButton(self.groupBox)
        self.pbt_go13.setGeometry(QtCore.QRect(260, 460, 75, 23))
        self.pbt_go13.setObjectName("pbt_go13")
        self.chb_go17 = QtWidgets.QCheckBox(self.groupBox)
        self.chb_go17.setGeometry(QtCore.QRect(20, 580, 91, 21))
        self.chb_go17.setObjectName("chb_go17")
        self.le_go15 = QtWidgets.QLineEdit(self.groupBox)
        self.le_go15.setGeometry(QtCore.QRect(130, 520, 113, 20))
        self.le_go15.setObjectName("le_go15")
        self.pbt_go19 = QtWidgets.QPushButton(self.groupBox)
        self.pbt_go19.setGeometry(QtCore.QRect(260, 640, 75, 23))
        self.pbt_go19.setObjectName("pbt_go19")
        self.pbt_go7 = QtWidgets.QPushButton(self.groupBox)
        self.pbt_go7.setGeometry(QtCore.QRect(260, 200, 75, 23))
        self.pbt_go7.setObjectName("pbt_go7")
        self.chb_go9 = QtWidgets.QCheckBox(self.groupBox)
        self.chb_go9.setGeometry(QtCore.QRect(20, 260, 101, 21))
        self.chb_go9.setObjectName("chb_go9")
        self.le_go21 = QtWidgets.QLineEdit(self.groupBox)
        self.le_go21.setGeometry(QtCore.QRect(130, 700, 113, 20))
        self.le_go21.setObjectName("le_go21")
        self.chb_go10 = QtWidgets.QCheckBox(self.groupBox)
        self.chb_go10.setGeometry(QtCore.QRect(20, 370, 101, 21))
        self.chb_go10.setObjectName("chb_go10")
        self.le_go12 = QtWidgets.QLineEdit(self.groupBox)
        self.le_go12.setGeometry(QtCore.QRect(130, 430, 113, 20))
        self.le_go12.setObjectName("le_go12")
        self.chb_go20 = QtWidgets.QCheckBox(self.groupBox)
        self.chb_go20.setGeometry(QtCore.QRect(20, 670, 81, 21))
        self.chb_go20.setObjectName("chb_go20")
        self.pbt_go6 = QtWidgets.QPushButton(self.groupBox)
        self.pbt_go6.setGeometry(QtCore.QRect(260, 170, 75, 23))
        self.pbt_go6.setObjectName("pbt_go6")
        self.le_go10 = QtWidgets.QLineEdit(self.groupBox)
        self.le_go10.setGeometry(QtCore.QRect(130, 370, 113, 20))
        self.le_go10.setObjectName("le_go10")
        self.chb_go2 = QtWidgets.QCheckBox(self.groupBox)
        self.chb_go2.setGeometry(QtCore.QRect(20, 50, 71, 21))
        self.chb_go2.setObjectName("chb_go2")
        self.pbt_go18 = QtWidgets.QPushButton(self.groupBox)
        self.pbt_go18.setGeometry(QtCore.QRect(260, 610, 75, 23))
        self.pbt_go18.setObjectName("pbt_go18")
        self.pbt_go16 = QtWidgets.QPushButton(self.groupBox)
        self.pbt_go16.setGeometry(QtCore.QRect(260, 550, 75, 23))
        self.pbt_go16.setObjectName("pbt_go16")
        self.chb_go16 = QtWidgets.QCheckBox(self.groupBox)
        self.chb_go16.setGeometry(QtCore.QRect(20, 550, 70, 17))
        self.chb_go16.setObjectName("chb_go16")
        self.le_go8 = QtWidgets.QLineEdit(self.groupBox)
        self.le_go8.setGeometry(QtCore.QRect(130, 230, 113, 20))
        self.le_go8.setObjectName("le_go8")
        self.pbt_go9 = QtWidgets.QPushButton(self.groupBox)
        self.pbt_go9.setGeometry(QtCore.QRect(260, 260, 75, 23))
        self.pbt_go9.setObjectName("pbt_go9")
        self.chb_go13 = QtWidgets.QCheckBox(self.groupBox)
        self.chb_go13.setGeometry(QtCore.QRect(20, 460, 91, 21))
        self.chb_go13.setObjectName("chb_go13")
        self.chb_go5 = QtWidgets.QCheckBox(self.groupBox)
        self.chb_go5.setGeometry(QtCore.QRect(20, 140, 111, 21))
        self.chb_go5.setObjectName("chb_go5")
        self.le_go2 = QtWidgets.QLineEdit(self.groupBox)
        self.le_go2.setGeometry(QtCore.QRect(130, 50, 113, 20))
        self.le_go2.setObjectName("le_go2")
        self.pbt_go15 = QtWidgets.QPushButton(self.groupBox)
        self.pbt_go15.setGeometry(QtCore.QRect(260, 520, 75, 23))
        self.pbt_go15.setObjectName("pbt_go15")
        self.le_go5 = QtWidgets.QLineEdit(self.groupBox)
        self.le_go5.setGeometry(QtCore.QRect(130, 140, 113, 20))
        self.le_go5.setObjectName("le_go5")
        self.pbt_go3 = QtWidgets.QPushButton(self.groupBox)
        self.pbt_go3.setGeometry(QtCore.QRect(260, 80, 75, 23))
        self.pbt_go3.setObjectName("pbt_go3")
        self.pbt_go11 = QtWidgets.QPushButton(self.groupBox)
        self.pbt_go11.setGeometry(QtCore.QRect(260, 400, 75, 23))
        self.pbt_go11.setObjectName("pbt_go11")
        self.chb_go18 = QtWidgets.QCheckBox(self.groupBox)
        self.chb_go18.setGeometry(QtCore.QRect(20, 610, 81, 21))
        self.chb_go18.setObjectName("chb_go18")
        self.le_go13 = QtWidgets.QLineEdit(self.groupBox)
        self.le_go13.setGeometry(QtCore.QRect(130, 460, 113, 20))
        self.le_go13.setObjectName("le_go13")
        self.pbt_go12 = QtWidgets.QPushButton(self.groupBox)
        self.pbt_go12.setGeometry(QtCore.QRect(260, 430, 75, 23))
        self.pbt_go12.setObjectName("pbt_go12")
        self.le_go6 = QtWidgets.QLineEdit(self.groupBox)
        self.le_go6.setGeometry(QtCore.QRect(130, 170, 113, 20))
        self.le_go6.setObjectName("le_go6")
        self.pbt_go4 = QtWidgets.QPushButton(self.groupBox)
        self.pbt_go4.setGeometry(QtCore.QRect(260, 110, 75, 23))
        self.pbt_go4.setObjectName("pbt_go4")
        self.chb_go6 = QtWidgets.QCheckBox(self.groupBox)
        self.chb_go6.setGeometry(QtCore.QRect(20, 170, 70, 17))
        self.chb_go6.setObjectName("chb_go6")
        self.pbt_go10 = QtWidgets.QPushButton(self.groupBox)
        self.pbt_go10.setGeometry(QtCore.QRect(260, 370, 75, 23))
        self.pbt_go10.setObjectName("pbt_go10")
        self.le_go18 = QtWidgets.QLineEdit(self.groupBox)
        self.le_go18.setGeometry(QtCore.QRect(130, 610, 113, 20))
        self.le_go18.setObjectName("le_go18")
        self.pbt_go14 = QtWidgets.QPushButton(self.groupBox)
        self.pbt_go14.setGeometry(QtCore.QRect(260, 490, 75, 23))
        self.pbt_go14.setObjectName("pbt_go14")
        self.chb_go8 = QtWidgets.QCheckBox(self.groupBox)
        self.chb_go8.setGeometry(QtCore.QRect(20, 230, 81, 17))
        self.chb_go8.setObjectName("chb_go8")
        self.chb_go12 = QtWidgets.QCheckBox(self.groupBox)
        self.chb_go12.setGeometry(QtCore.QRect(20, 430, 70, 17))
        self.chb_go12.setObjectName("chb_go12")
        self.le_go17 = QtWidgets.QLineEdit(self.groupBox)
        self.le_go17.setGeometry(QtCore.QRect(130, 580, 113, 20))
        self.le_go17.setObjectName("le_go17")
        self.le_go9 = QtWidgets.QLineEdit(self.groupBox)
        self.le_go9.setGeometry(QtCore.QRect(130, 260, 113, 20))
        self.le_go9.setObjectName("le_go9")
        self.chb_go21 = QtWidgets.QCheckBox(self.groupBox)
        self.chb_go21.setGeometry(QtCore.QRect(20, 700, 70, 17))
        self.chb_go21.setObjectName("chb_go21")
        self.chb_go19 = QtWidgets.QCheckBox(self.groupBox)
        self.chb_go19.setGeometry(QtCore.QRect(20, 640, 91, 21))
        self.chb_go19.setObjectName("chb_go19")
        self.pbt_go20 = QtWidgets.QPushButton(self.groupBox)
        self.pbt_go20.setGeometry(QtCore.QRect(260, 670, 75, 23))
        self.pbt_go20.setObjectName("pbt_go20")
        self.pbt_go17 = QtWidgets.QPushButton(self.groupBox)
        self.pbt_go17.setGeometry(QtCore.QRect(260, 580, 75, 23))
        self.pbt_go17.setObjectName("pbt_go17")
        self.chb_go1 = QtWidgets.QCheckBox(self.groupBox)
        self.chb_go1.setGeometry(QtCore.QRect(20, 20, 91, 21))
        self.chb_go1.setObjectName("chb_go1")
        self.chb_go3 = QtWidgets.QCheckBox(self.groupBox)
        self.chb_go3.setGeometry(QtCore.QRect(20, 80, 81, 21))
        self.chb_go3.setObjectName("chb_go3")
        self.le_go14 = QtWidgets.QLineEdit(self.groupBox)
        self.le_go14.setGeometry(QtCore.QRect(130, 490, 113, 20))
        self.le_go14.setObjectName("le_go14")
        self.pbt_go8 = QtWidgets.QPushButton(self.groupBox)
        self.pbt_go8.setGeometry(QtCore.QRect(260, 230, 75, 23))
        self.pbt_go8.setObjectName("pbt_go8")
        self.le_go7 = QtWidgets.QLineEdit(self.groupBox)
        self.le_go7.setGeometry(QtCore.QRect(130, 200, 113, 20))
        self.le_go7.setObjectName("le_go7")
        self.pbt_go1 = QtWidgets.QPushButton(self.groupBox)
        self.pbt_go1.setGeometry(QtCore.QRect(260, 20, 75, 23))
        self.pbt_go1.setObjectName("pbt_go1")
        self.groupBox_2 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_2.setGeometry(QtCore.QRect(380, 10, 361, 741))
        self.groupBox_2.setObjectName("groupBox_2")
        self.le_gp7 = QtWidgets.QLineEdit(self.groupBox_2)
        self.le_gp7.setGeometry(QtCore.QRect(130, 200, 113, 20))
        self.le_gp7.setObjectName("le_gp7")
        self.pbt_gp20 = QtWidgets.QPushButton(self.groupBox_2)
        self.pbt_gp20.setGeometry(QtCore.QRect(260, 670, 75, 23))
        self.pbt_gp20.setObjectName("pbt_gp20")
        self.le_gp13 = QtWidgets.QLineEdit(self.groupBox_2)
        self.le_gp13.setGeometry(QtCore.QRect(130, 460, 113, 20))
        self.le_gp13.setObjectName("le_gp13")
        self.pbt_gp19 = QtWidgets.QPushButton(self.groupBox_2)
        self.pbt_gp19.setGeometry(QtCore.QRect(260, 640, 75, 23))
        self.pbt_gp19.setObjectName("pbt_gp19")
        self.pbt_gp21 = QtWidgets.QPushButton(self.groupBox_2)
        self.pbt_gp21.setGeometry(QtCore.QRect(260, 700, 75, 23))
        self.pbt_gp21.setObjectName("pbt_gp21")
        self.pbt_gp11 = QtWidgets.QPushButton(self.groupBox_2)
        self.pbt_gp11.setGeometry(QtCore.QRect(260, 400, 75, 23))
        self.pbt_gp11.setObjectName("pbt_gp11")
        self.le_gp17 = QtWidgets.QLineEdit(self.groupBox_2)
        self.le_gp17.setGeometry(QtCore.QRect(130, 580, 113, 20))
        self.le_gp17.setObjectName("le_gp17")
        self.pbt_gp6 = QtWidgets.QPushButton(self.groupBox_2)
        self.pbt_gp6.setGeometry(QtCore.QRect(260, 170, 75, 23))
        self.pbt_gp6.setObjectName("pbt_gp6")
        self.chb_gp19 = QtWidgets.QCheckBox(self.groupBox_2)
        self.chb_gp19.setGeometry(QtCore.QRect(20, 640, 91, 21))
        self.chb_gp19.setObjectName("chb_gp19")
        self.le_gp6 = QtWidgets.QLineEdit(self.groupBox_2)
        self.le_gp6.setGeometry(QtCore.QRect(130, 170, 113, 20))
        self.le_gp6.setObjectName("le_gp6")
        self.le_gp2 = QtWidgets.QLineEdit(self.groupBox_2)
        self.le_gp2.setGeometry(QtCore.QRect(130, 50, 113, 20))
        self.le_gp2.setObjectName("le_gp2")
        self.le_gp8 = QtWidgets.QLineEdit(self.groupBox_2)
        self.le_gp8.setGeometry(QtCore.QRect(130, 230, 113, 20))
        self.le_gp8.setObjectName("le_gp8")
        self.pbt_gp15 = QtWidgets.QPushButton(self.groupBox_2)
        self.pbt_gp15.setGeometry(QtCore.QRect(260, 520, 75, 23))
        self.pbt_gp15.setObjectName("pbt_gp15")
        self.pbt_gp8 = QtWidgets.QPushButton(self.groupBox_2)
        self.pbt_gp8.setGeometry(QtCore.QRect(260, 230, 75, 23))
        self.pbt_gp8.setObjectName("pbt_gp8")
        self.le_gp10 = QtWidgets.QLineEdit(self.groupBox_2)
        self.le_gp10.setGeometry(QtCore.QRect(130, 370, 113, 20))
        self.le_gp10.setObjectName("le_gp10")
        self.chb_gp9 = QtWidgets.QCheckBox(self.groupBox_2)
        self.chb_gp9.setGeometry(QtCore.QRect(20, 260, 101, 21))
        self.chb_gp9.setObjectName("chb_gp9")
        self.pbt_gp5 = QtWidgets.QPushButton(self.groupBox_2)
        self.pbt_gp5.setGeometry(QtCore.QRect(260, 140, 75, 23))
        self.pbt_gp5.setObjectName("pbt_gp5")
        self.pbt_gp2 = QtWidgets.QPushButton(self.groupBox_2)
        self.pbt_gp2.setGeometry(QtCore.QRect(260, 50, 75, 23))
        self.pbt_gp2.setObjectName("pbt_gp2")
        self.chb_gp1 = QtWidgets.QCheckBox(self.groupBox_2)
        self.chb_gp1.setGeometry(QtCore.QRect(20, 20, 91, 21))
        self.chb_gp1.setObjectName("chb_gp1")
        self.chb_gp17 = QtWidgets.QCheckBox(self.groupBox_2)
        self.chb_gp17.setGeometry(QtCore.QRect(20, 580, 91, 21))
        self.chb_gp17.setObjectName("chb_gp17")
        self.chb_gp8 = QtWidgets.QCheckBox(self.groupBox_2)
        self.chb_gp8.setGeometry(QtCore.QRect(20, 230, 70, 17))
        self.chb_gp8.setObjectName("chb_gp8")
        self.le_gp20 = QtWidgets.QLineEdit(self.groupBox_2)
        self.le_gp20.setGeometry(QtCore.QRect(130, 670, 113, 20))
        self.le_gp20.setObjectName("le_gp20")
        self.le_gp11 = QtWidgets.QLineEdit(self.groupBox_2)
        self.le_gp11.setGeometry(QtCore.QRect(130, 400, 113, 20))
        self.le_gp11.setObjectName("le_gp11")
        self.le_gp15 = QtWidgets.QLineEdit(self.groupBox_2)
        self.le_gp15.setGeometry(QtCore.QRect(130, 520, 113, 20))
        self.le_gp15.setObjectName("le_gp15")
        self.chb_gp15 = QtWidgets.QCheckBox(self.groupBox_2)
        self.chb_gp15.setGeometry(QtCore.QRect(20, 520, 101, 21))
        self.chb_gp15.setObjectName("chb_gp15")
        self.chb_gp12 = QtWidgets.QCheckBox(self.groupBox_2)
        self.chb_gp12.setGeometry(QtCore.QRect(20, 430, 70, 17))
        self.chb_gp12.setObjectName("chb_gp12")
        self.le_gp16 = QtWidgets.QLineEdit(self.groupBox_2)
        self.le_gp16.setGeometry(QtCore.QRect(130, 550, 113, 20))
        self.le_gp16.setObjectName("le_gp16")
        self.le_gp4 = QtWidgets.QLineEdit(self.groupBox_2)
        self.le_gp4.setGeometry(QtCore.QRect(130, 110, 113, 20))
        self.le_gp4.setObjectName("le_gp4")
        self.pbt_gp9 = QtWidgets.QPushButton(self.groupBox_2)
        self.pbt_gp9.setGeometry(QtCore.QRect(260, 260, 75, 23))
        self.pbt_gp9.setObjectName("pbt_gp9")
        self.pbt_gp10 = QtWidgets.QPushButton(self.groupBox_2)
        self.pbt_gp10.setGeometry(QtCore.QRect(260, 370, 75, 23))
        self.pbt_gp10.setObjectName("pbt_gp10")
        self.pbt_gp18 = QtWidgets.QPushButton(self.groupBox_2)
        self.pbt_gp18.setGeometry(QtCore.QRect(260, 610, 75, 23))
        self.pbt_gp18.setObjectName("pbt_gp18")
        self.chb_gp2 = QtWidgets.QCheckBox(self.groupBox_2)
        self.chb_gp2.setGeometry(QtCore.QRect(20, 50, 71, 21))
        self.chb_gp2.setObjectName("chb_gp2")
        self.pbt_gp3 = QtWidgets.QPushButton(self.groupBox_2)
        self.pbt_gp3.setGeometry(QtCore.QRect(260, 80, 75, 23))
        self.pbt_gp3.setObjectName("pbt_gp3")
        self.chb_gp4 = QtWidgets.QCheckBox(self.groupBox_2)
        self.chb_gp4.setGeometry(QtCore.QRect(20, 110, 70, 17))
        self.chb_gp4.setObjectName("chb_gp4")
        self.chb_gp14 = QtWidgets.QCheckBox(self.groupBox_2)
        self.chb_gp14.setGeometry(QtCore.QRect(20, 490, 70, 17))
        self.chb_gp14.setObjectName("chb_gp14")
        self.pbt_gp7 = QtWidgets.QPushButton(self.groupBox_2)
        self.pbt_gp7.setGeometry(QtCore.QRect(260, 200, 75, 23))
        self.pbt_gp7.setObjectName("pbt_gp7")
        self.le_gp1 = QtWidgets.QLineEdit(self.groupBox_2)
        self.le_gp1.setGeometry(QtCore.QRect(130, 20, 113, 20))
        self.le_gp1.setObjectName("le_gp1")
        self.le_gp18 = QtWidgets.QLineEdit(self.groupBox_2)
        self.le_gp18.setGeometry(QtCore.QRect(130, 610, 113, 20))
        self.le_gp18.setObjectName("le_gp18")
        self.le_gp14 = QtWidgets.QLineEdit(self.groupBox_2)
        self.le_gp14.setGeometry(QtCore.QRect(130, 490, 113, 20))
        self.le_gp14.setObjectName("le_gp14")
        self.chb_gp6 = QtWidgets.QCheckBox(self.groupBox_2)
        self.chb_gp6.setGeometry(QtCore.QRect(20, 170, 70, 17))
        self.chb_gp6.setObjectName("chb_gp6")
        self.le_gp3 = QtWidgets.QLineEdit(self.groupBox_2)
        self.le_gp3.setGeometry(QtCore.QRect(130, 80, 113, 20))
        self.le_gp3.setObjectName("le_gp3")
        self.chb_gp20 = QtWidgets.QCheckBox(self.groupBox_2)
        self.chb_gp20.setGeometry(QtCore.QRect(20, 670, 81, 21))
        self.chb_gp20.setObjectName("chb_gp20")
        self.le_gp21 = QtWidgets.QLineEdit(self.groupBox_2)
        self.le_gp21.setGeometry(QtCore.QRect(130, 700, 113, 20))
        self.le_gp21.setObjectName("le_gp21")
        self.pbt_gp13 = QtWidgets.QPushButton(self.groupBox_2)
        self.pbt_gp13.setGeometry(QtCore.QRect(260, 460, 75, 23))
        self.pbt_gp13.setObjectName("pbt_gp13")
        self.pbt_gp12 = QtWidgets.QPushButton(self.groupBox_2)
        self.pbt_gp12.setGeometry(QtCore.QRect(260, 430, 75, 23))
        self.pbt_gp12.setObjectName("pbt_gp12")
        self.chb_gp7 = QtWidgets.QCheckBox(self.groupBox_2)
        self.chb_gp7.setGeometry(QtCore.QRect(20, 200, 70, 17))
        self.chb_gp7.setObjectName("chb_gp7")
        self.le_gp12 = QtWidgets.QLineEdit(self.groupBox_2)
        self.le_gp12.setGeometry(QtCore.QRect(130, 430, 113, 20))
        self.le_gp12.setObjectName("le_gp12")
        self.chb_gp10 = QtWidgets.QCheckBox(self.groupBox_2)
        self.chb_gp10.setGeometry(QtCore.QRect(20, 370, 101, 21))
        self.chb_gp10.setObjectName("chb_gp10")
        self.pbt_gp4 = QtWidgets.QPushButton(self.groupBox_2)
        self.pbt_gp4.setGeometry(QtCore.QRect(260, 110, 75, 23))
        self.pbt_gp4.setObjectName("pbt_gp4")
        self.chb_gp21 = QtWidgets.QCheckBox(self.groupBox_2)
        self.chb_gp21.setGeometry(QtCore.QRect(20, 700, 70, 17))
        self.chb_gp21.setObjectName("chb_gp21")
        self.le_gp9 = QtWidgets.QLineEdit(self.groupBox_2)
        self.le_gp9.setGeometry(QtCore.QRect(130, 260, 113, 20))
        self.le_gp9.setObjectName("le_gp9")
        self.chb_gp5 = QtWidgets.QCheckBox(self.groupBox_2)
        self.chb_gp5.setGeometry(QtCore.QRect(20, 140, 111, 21))
        self.chb_gp5.setObjectName("chb_gp5")
        self.chb_gp18 = QtWidgets.QCheckBox(self.groupBox_2)
        self.chb_gp18.setGeometry(QtCore.QRect(20, 610, 81, 21))
        self.chb_gp18.setObjectName("chb_gp18")
        self.pbt_gp16 = QtWidgets.QPushButton(self.groupBox_2)
        self.pbt_gp16.setGeometry(QtCore.QRect(260, 550, 75, 23))
        self.pbt_gp16.setObjectName("pbt_gp16")
        self.chb_gp11 = QtWidgets.QCheckBox(self.groupBox_2)
        self.chb_gp11.setGeometry(QtCore.QRect(20, 400, 70, 17))
        self.chb_gp11.setObjectName("chb_gp11")
        self.chb_gp13 = QtWidgets.QCheckBox(self.groupBox_2)
        self.chb_gp13.setGeometry(QtCore.QRect(20, 460, 91, 21))
        self.chb_gp13.setObjectName("chb_gp13")
        self.le_gp5 = QtWidgets.QLineEdit(self.groupBox_2)
        self.le_gp5.setGeometry(QtCore.QRect(130, 140, 113, 20))
        self.le_gp5.setObjectName("le_gp5")
        self.pbt_gp14 = QtWidgets.QPushButton(self.groupBox_2)
        self.pbt_gp14.setGeometry(QtCore.QRect(260, 490, 75, 23))
        self.pbt_gp14.setObjectName("pbt_gp14")
        self.le_gp19 = QtWidgets.QLineEdit(self.groupBox_2)
        self.le_gp19.setGeometry(QtCore.QRect(130, 640, 113, 20))
        self.le_gp19.setObjectName("le_gp19")
        self.chb_gp3 = QtWidgets.QCheckBox(self.groupBox_2)
        self.chb_gp3.setGeometry(QtCore.QRect(20, 80, 81, 21))
        self.chb_gp3.setObjectName("chb_gp3")
        self.chb_gp16 = QtWidgets.QCheckBox(self.groupBox_2)
        self.chb_gp16.setGeometry(QtCore.QRect(20, 550, 70, 17))
        self.chb_gp16.setObjectName("chb_gp16")
        self.pbt_gp1 = QtWidgets.QPushButton(self.groupBox_2)
        self.pbt_gp1.setGeometry(QtCore.QRect(260, 20, 75, 23))
        self.pbt_gp1.setObjectName("pbt_gp1")
        self.pbt_gp17 = QtWidgets.QPushButton(self.groupBox_2)
        self.pbt_gp17.setGeometry(QtCore.QRect(260, 580, 75, 23))
        self.pbt_gp17.setObjectName("pbt_gp17")
        self.groupBox_3 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_3.setGeometry(QtCore.QRect(750, 10, 441, 791))
        self.groupBox_3.setObjectName("groupBox_3")
        self.chb_tbl2 = QtWidgets.QCheckBox(self.groupBox_3)
        self.chb_tbl2.setGeometry(QtCore.QRect(20, 40, 71, 21))
        self.chb_tbl2.setObjectName("chb_tbl2")
        self.le_tbl12 = QtWidgets.QLineEdit(self.groupBox_3)
        self.le_tbl12.setGeometry(QtCore.QRect(180, 240, 113, 20))
        self.le_tbl12.setObjectName("le_tbl12")
        self.chb_tbl18 = QtWidgets.QCheckBox(self.groupBox_3)
        self.chb_tbl18.setGeometry(QtCore.QRect(20, 360, 121, 21))
        self.chb_tbl18.setObjectName("chb_tbl18")
        self.chb_tbl28 = QtWidgets.QCheckBox(self.groupBox_3)
        self.chb_tbl28.setGeometry(QtCore.QRect(20, 560, 131, 21))
        self.chb_tbl28.setObjectName("chb_tbl28")
        self.le_tbl30 = QtWidgets.QLineEdit(self.groupBox_3)
        self.le_tbl30.setGeometry(QtCore.QRect(180, 600, 113, 20))
        self.le_tbl30.setObjectName("le_tbl30")
        self.chb_tbl8 = QtWidgets.QCheckBox(self.groupBox_3)
        self.chb_tbl8.setGeometry(QtCore.QRect(20, 160, 70, 17))
        self.chb_tbl8.setObjectName("chb_tbl8")
        self.chb_tbl5 = QtWidgets.QCheckBox(self.groupBox_3)
        self.chb_tbl5.setGeometry(QtCore.QRect(20, 100, 111, 21))
        self.chb_tbl5.setObjectName("chb_tbl5")
        self.le_tbl27 = QtWidgets.QLineEdit(self.groupBox_3)
        self.le_tbl27.setGeometry(QtCore.QRect(180, 540, 113, 20))
        self.le_tbl27.setObjectName("le_tbl27")
        self.pbt_tbl20 = QtWidgets.QPushButton(self.groupBox_3)
        self.pbt_tbl20.setGeometry(QtCore.QRect(310, 400, 75, 23))
        self.pbt_tbl20.setObjectName("pbt_tbl20")
        self.pbt_tbl15 = QtWidgets.QPushButton(self.groupBox_3)
        self.pbt_tbl15.setGeometry(QtCore.QRect(310, 300, 75, 23))
        self.pbt_tbl15.setObjectName("pbt_tbl15")
        self.le_tbl29 = QtWidgets.QLineEdit(self.groupBox_3)
        self.le_tbl29.setGeometry(QtCore.QRect(180, 580, 113, 20))
        self.le_tbl29.setObjectName("le_tbl29")
        self.pbt_tbl16 = QtWidgets.QPushButton(self.groupBox_3)
        self.pbt_tbl16.setGeometry(QtCore.QRect(310, 320, 75, 23))
        self.pbt_tbl16.setObjectName("pbt_tbl16")
        self.pbt_tbl4 = QtWidgets.QPushButton(self.groupBox_3)
        self.pbt_tbl4.setGeometry(QtCore.QRect(310, 80, 75, 23))
        self.pbt_tbl4.setObjectName("pbt_tbl4")
        self.le_tbl1 = QtWidgets.QLineEdit(self.groupBox_3)
        self.le_tbl1.setGeometry(QtCore.QRect(180, 20, 113, 20))
        self.le_tbl1.setObjectName("le_tbl1")
        self.le_tbl18 = QtWidgets.QLineEdit(self.groupBox_3)
        self.le_tbl18.setGeometry(QtCore.QRect(180, 360, 113, 20))
        self.le_tbl18.setObjectName("le_tbl18")
        self.le_tbl10 = QtWidgets.QLineEdit(self.groupBox_3)
        self.le_tbl10.setGeometry(QtCore.QRect(180, 200, 113, 20))
        self.le_tbl10.setObjectName("le_tbl10")
        self.pbt_tbl24 = QtWidgets.QPushButton(self.groupBox_3)
        self.pbt_tbl24.setGeometry(QtCore.QRect(310, 480, 75, 23))
        self.pbt_tbl24.setObjectName("pbt_tbl24")
        self.chb_tbl15 = QtWidgets.QCheckBox(self.groupBox_3)
        self.chb_tbl15.setGeometry(QtCore.QRect(20, 300, 131, 21))
        self.chb_tbl15.setObjectName("chb_tbl15")
        self.pbt_tbl21 = QtWidgets.QPushButton(self.groupBox_3)
        self.pbt_tbl21.setGeometry(QtCore.QRect(310, 420, 75, 23))
        self.pbt_tbl21.setObjectName("pbt_tbl21")
        self.pbt_tbl23 = QtWidgets.QPushButton(self.groupBox_3)
        self.pbt_tbl23.setGeometry(QtCore.QRect(310, 460, 75, 23))
        self.pbt_tbl23.setObjectName("pbt_tbl23")
        self.pbt_tbl3 = QtWidgets.QPushButton(self.groupBox_3)
        self.pbt_tbl3.setGeometry(QtCore.QRect(310, 60, 75, 23))
        self.pbt_tbl3.setObjectName("pbt_tbl3")
        self.pbt_tbl32_2 = QtWidgets.QPushButton(self.groupBox_3)
        self.pbt_tbl32_2.setGeometry(QtCore.QRect(310, 640, 75, 23))
        self.pbt_tbl32_2.setObjectName("pbt_tbl32_2")
        self.le_tbl2 = QtWidgets.QLineEdit(self.groupBox_3)
        self.le_tbl2.setGeometry(QtCore.QRect(180, 40, 113, 20))
        self.le_tbl2.setObjectName("le_tbl2")
        self.le_tbl7 = QtWidgets.QLineEdit(self.groupBox_3)
        self.le_tbl7.setGeometry(QtCore.QRect(180, 140, 113, 20))
        self.le_tbl7.setObjectName("le_tbl7")
        self.pbt_tbl14 = QtWidgets.QPushButton(self.groupBox_3)
        self.pbt_tbl14.setGeometry(QtCore.QRect(310, 280, 75, 23))
        self.pbt_tbl14.setObjectName("pbt_tbl14")
        self.pbt_tbl7 = QtWidgets.QPushButton(self.groupBox_3)
        self.pbt_tbl7.setGeometry(QtCore.QRect(310, 140, 75, 23))
        self.pbt_tbl7.setObjectName("pbt_tbl7")
        self.pbt_tbl28 = QtWidgets.QPushButton(self.groupBox_3)
        self.pbt_tbl28.setGeometry(QtCore.QRect(310, 560, 75, 23))
        self.pbt_tbl28.setObjectName("pbt_tbl28")
        self.le_tbl33 = QtWidgets.QLineEdit(self.groupBox_3)
        self.le_tbl33.setGeometry(QtCore.QRect(180, 660, 113, 20))
        self.le_tbl33.setObjectName("le_tbl33")
        self.chb_tbl16 = QtWidgets.QCheckBox(self.groupBox_3)
        self.chb_tbl16.setGeometry(QtCore.QRect(20, 320, 70, 17))
        self.chb_tbl16.setObjectName("chb_tbl16")
        self.le_tbl26 = QtWidgets.QLineEdit(self.groupBox_3)
        self.le_tbl26.setGeometry(QtCore.QRect(180, 520, 113, 20))
        self.le_tbl26.setObjectName("le_tbl26")
        self.chb_tbl32 = QtWidgets.QCheckBox(self.groupBox_3)
        self.chb_tbl32.setGeometry(QtCore.QRect(20, 640, 151, 21))
        self.chb_tbl32.setObjectName("chb_tbl32")
        self.pbt_tbl8 = QtWidgets.QPushButton(self.groupBox_3)
        self.pbt_tbl8.setGeometry(QtCore.QRect(310, 160, 75, 23))
        self.pbt_tbl8.setObjectName("pbt_tbl8")
        self.chb_tbl9 = QtWidgets.QCheckBox(self.groupBox_3)
        self.chb_tbl9.setGeometry(QtCore.QRect(20, 180, 101, 21))
        self.chb_tbl9.setObjectName("chb_tbl9")
        self.pbt_tbl31_2 = QtWidgets.QPushButton(self.groupBox_3)
        self.pbt_tbl31_2.setGeometry(QtCore.QRect(310, 620, 75, 23))
        self.pbt_tbl31_2.setObjectName("pbt_tbl31_2")
        self.le_tbl9 = QtWidgets.QLineEdit(self.groupBox_3)
        self.le_tbl9.setGeometry(QtCore.QRect(180, 180, 113, 20))
        self.le_tbl9.setObjectName("le_tbl9")
        self.pbt_tbl36 = QtWidgets.QPushButton(self.groupBox_3)
        self.pbt_tbl36.setGeometry(QtCore.QRect(310, 720, 75, 23))
        self.pbt_tbl36.setObjectName("pbt_tbl36")
        self.chb_tbl27 = QtWidgets.QCheckBox(self.groupBox_3)
        self.chb_tbl27.setGeometry(QtCore.QRect(20, 540, 151, 21))
        self.chb_tbl27.setObjectName("chb_tbl27")
        self.chb_tbl31 = QtWidgets.QCheckBox(self.groupBox_3)
        self.chb_tbl31.setGeometry(QtCore.QRect(20, 620, 141, 21))
        self.chb_tbl31.setObjectName("chb_tbl31")
        self.le_tbl6 = QtWidgets.QLineEdit(self.groupBox_3)
        self.le_tbl6.setGeometry(QtCore.QRect(180, 120, 113, 20))
        self.le_tbl6.setObjectName("le_tbl6")
        self.le_tbl3 = QtWidgets.QLineEdit(self.groupBox_3)
        self.le_tbl3.setGeometry(QtCore.QRect(180, 60, 113, 20))
        self.le_tbl3.setObjectName("le_tbl3")
        self.pbt_tbl137 = QtWidgets.QPushButton(self.groupBox_3)
        self.pbt_tbl137.setGeometry(QtCore.QRect(310, 740, 75, 23))
        self.pbt_tbl137.setObjectName("pbt_tbl137")
        self.le_tbl17 = QtWidgets.QLineEdit(self.groupBox_3)
        self.le_tbl17.setGeometry(QtCore.QRect(180, 340, 113, 20))
        self.le_tbl17.setObjectName("le_tbl17")
        self.pbt_tbl22 = QtWidgets.QPushButton(self.groupBox_3)
        self.pbt_tbl22.setGeometry(QtCore.QRect(310, 440, 75, 23))
        self.pbt_tbl22.setObjectName("pbt_tbl22")
        self.le_tbl11 = QtWidgets.QLineEdit(self.groupBox_3)
        self.le_tbl11.setGeometry(QtCore.QRect(180, 220, 113, 20))
        self.le_tbl11.setObjectName("le_tbl11")
        self.le_tbl35 = QtWidgets.QLineEdit(self.groupBox_3)
        self.le_tbl35.setGeometry(QtCore.QRect(180, 700, 113, 20))
        self.le_tbl35.setObjectName("le_tbl35")
        self.le_tbl14 = QtWidgets.QLineEdit(self.groupBox_3)
        self.le_tbl14.setGeometry(QtCore.QRect(180, 280, 113, 20))
        self.le_tbl14.setObjectName("le_tbl14")
        self.le_tbl31 = QtWidgets.QLineEdit(self.groupBox_3)
        self.le_tbl31.setGeometry(QtCore.QRect(180, 620, 113, 20))
        self.le_tbl31.setObjectName("le_tbl31")
        self.chb_tbl29 = QtWidgets.QCheckBox(self.groupBox_3)
        self.chb_tbl29.setGeometry(QtCore.QRect(20, 580, 131, 21))
        self.chb_tbl29.setObjectName("chb_tbl29")
        self.chb_tbl25 = QtWidgets.QCheckBox(self.groupBox_3)
        self.chb_tbl25.setGeometry(QtCore.QRect(20, 500, 161, 17))
        self.chb_tbl25.setObjectName("chb_tbl25")
        self.chb_tbl21 = QtWidgets.QCheckBox(self.groupBox_3)
        self.chb_tbl21.setGeometry(QtCore.QRect(20, 420, 131, 21))
        self.chb_tbl21.setObjectName("chb_tbl21")
        self.pbt_tbl27 = QtWidgets.QPushButton(self.groupBox_3)
        self.pbt_tbl27.setGeometry(QtCore.QRect(310, 540, 75, 23))
        self.pbt_tbl27.setObjectName("pbt_tbl27")
        self.chb_tbl19 = QtWidgets.QCheckBox(self.groupBox_3)
        self.chb_tbl19.setGeometry(QtCore.QRect(20, 380, 91, 21))
        self.chb_tbl19.setObjectName("chb_tbl19")
        self.pbt_tbl25 = QtWidgets.QPushButton(self.groupBox_3)
        self.pbt_tbl25.setGeometry(QtCore.QRect(310, 500, 75, 23))
        self.pbt_tbl25.setObjectName("pbt_tbl25")
        self.pbt_tbl29_2 = QtWidgets.QPushButton(self.groupBox_3)
        self.pbt_tbl29_2.setGeometry(QtCore.QRect(310, 580, 75, 23))
        self.pbt_tbl29_2.setObjectName("pbt_tbl29_2")
        self.pbt_tbl26 = QtWidgets.QPushButton(self.groupBox_3)
        self.pbt_tbl26.setGeometry(QtCore.QRect(310, 520, 75, 23))
        self.pbt_tbl26.setObjectName("pbt_tbl26")
        self.le_tbl13 = QtWidgets.QLineEdit(self.groupBox_3)
        self.le_tbl13.setGeometry(QtCore.QRect(180, 260, 113, 20))
        self.le_tbl13.setObjectName("le_tbl13")
        self.pbt_tbl33_2 = QtWidgets.QPushButton(self.groupBox_3)
        self.pbt_tbl33_2.setGeometry(QtCore.QRect(310, 660, 75, 23))
        self.pbt_tbl33_2.setObjectName("pbt_tbl33_2")
        self.chb_tbl30 = QtWidgets.QCheckBox(self.groupBox_3)
        self.chb_tbl30.setGeometry(QtCore.QRect(20, 600, 141, 21))
        self.chb_tbl30.setObjectName("chb_tbl30")
        self.le_tbl4 = QtWidgets.QLineEdit(self.groupBox_3)
        self.le_tbl4.setGeometry(QtCore.QRect(180, 80, 113, 20))
        self.le_tbl4.setObjectName("le_tbl4")
        self.pbt_tbl34_2 = QtWidgets.QPushButton(self.groupBox_3)
        self.pbt_tbl34_2.setGeometry(QtCore.QRect(310, 680, 75, 23))
        self.pbt_tbl34_2.setObjectName("pbt_tbl34_2")
        self.pbt_tbl11 = QtWidgets.QPushButton(self.groupBox_3)
        self.pbt_tbl11.setGeometry(QtCore.QRect(310, 220, 75, 23))
        self.pbt_tbl11.setObjectName("pbt_tbl11")
        self.le_tbl23 = QtWidgets.QLineEdit(self.groupBox_3)
        self.le_tbl23.setGeometry(QtCore.QRect(180, 460, 113, 20))
        self.le_tbl23.setObjectName("le_tbl23")
        self.chb_tbl4 = QtWidgets.QCheckBox(self.groupBox_3)
        self.chb_tbl4.setGeometry(QtCore.QRect(20, 80, 121, 21))
        self.chb_tbl4.setObjectName("chb_tbl4")
        self.le_tbl21 = QtWidgets.QLineEdit(self.groupBox_3)
        self.le_tbl21.setGeometry(QtCore.QRect(180, 420, 113, 20))
        self.le_tbl21.setObjectName("le_tbl21")
        self.pbt_tbl10 = QtWidgets.QPushButton(self.groupBox_3)
        self.pbt_tbl10.setGeometry(QtCore.QRect(310, 200, 75, 23))
        self.pbt_tbl10.setObjectName("pbt_tbl10")
        self.pbt_tbl18 = QtWidgets.QPushButton(self.groupBox_3)
        self.pbt_tbl18.setGeometry(QtCore.QRect(310, 360, 75, 23))
        self.pbt_tbl18.setObjectName("pbt_tbl18")
        self.chb_tbl24 = QtWidgets.QCheckBox(self.groupBox_3)
        self.chb_tbl24.setGeometry(QtCore.QRect(20, 480, 151, 21))
        self.chb_tbl24.setObjectName("chb_tbl24")
        self.pbt_tbl1 = QtWidgets.QPushButton(self.groupBox_3)
        self.pbt_tbl1.setGeometry(QtCore.QRect(310, 20, 75, 23))
        self.pbt_tbl1.setObjectName("pbt_tbl1")
        self.pbt_tbl2 = QtWidgets.QPushButton(self.groupBox_3)
        self.pbt_tbl2.setGeometry(QtCore.QRect(310, 40, 75, 23))
        self.pbt_tbl2.setObjectName("pbt_tbl2")
        self.le_tbl20 = QtWidgets.QLineEdit(self.groupBox_3)
        self.le_tbl20.setGeometry(QtCore.QRect(180, 400, 113, 20))
        self.le_tbl20.setObjectName("le_tbl20")
        self.chb_tbl35 = QtWidgets.QCheckBox(self.groupBox_3)
        self.chb_tbl35.setGeometry(QtCore.QRect(20, 700, 91, 17))
        self.chb_tbl35.setObjectName("chb_tbl35")
        self.pbt_tbl19 = QtWidgets.QPushButton(self.groupBox_3)
        self.pbt_tbl19.setGeometry(QtCore.QRect(310, 380, 75, 23))
        self.pbt_tbl19.setObjectName("pbt_tbl19")
        self.le_tbl37 = QtWidgets.QLineEdit(self.groupBox_3)
        self.le_tbl37.setGeometry(QtCore.QRect(180, 740, 113, 20))
        self.le_tbl37.setObjectName("le_tbl37")
        self.pbt_tbl6 = QtWidgets.QPushButton(self.groupBox_3)
        self.pbt_tbl6.setGeometry(QtCore.QRect(310, 120, 75, 23))
        self.pbt_tbl6.setObjectName("pbt_tbl6")
        self.chb_tbl33 = QtWidgets.QCheckBox(self.groupBox_3)
        self.chb_tbl33.setGeometry(QtCore.QRect(20, 660, 161, 21))
        self.chb_tbl33.setObjectName("chb_tbl33")
        self.le_tbl19 = QtWidgets.QLineEdit(self.groupBox_3)
        self.le_tbl19.setGeometry(QtCore.QRect(180, 380, 113, 20))
        self.le_tbl19.setObjectName("le_tbl19")
        self.chb_tbl12 = QtWidgets.QCheckBox(self.groupBox_3)
        self.chb_tbl12.setGeometry(QtCore.QRect(20, 240, 141, 21))
        self.chb_tbl12.setObjectName("chb_tbl12")
        self.chb_tbl6 = QtWidgets.QCheckBox(self.groupBox_3)
        self.chb_tbl6.setGeometry(QtCore.QRect(20, 120, 121, 21))
        self.chb_tbl6.setObjectName("chb_tbl6")
        self.chb_tbl22 = QtWidgets.QCheckBox(self.groupBox_3)
        self.chb_tbl22.setGeometry(QtCore.QRect(20, 440, 141, 21))
        self.chb_tbl22.setObjectName("chb_tbl22")
        self.le_tbl32 = QtWidgets.QLineEdit(self.groupBox_3)
        self.le_tbl32.setGeometry(QtCore.QRect(180, 640, 113, 20))
        self.le_tbl32.setObjectName("le_tbl32")
        self.pbt_tbl30_2 = QtWidgets.QPushButton(self.groupBox_3)
        self.pbt_tbl30_2.setGeometry(QtCore.QRect(310, 600, 75, 23))
        self.pbt_tbl30_2.setObjectName("pbt_tbl30_2")
        self.chb_tbl20 = QtWidgets.QCheckBox(self.groupBox_3)
        self.chb_tbl20.setGeometry(QtCore.QRect(20, 400, 151, 21))
        self.chb_tbl20.setObjectName("chb_tbl20")
        self.chb_tbl23 = QtWidgets.QCheckBox(self.groupBox_3)
        self.chb_tbl23.setGeometry(QtCore.QRect(20, 460, 151, 21))
        self.chb_tbl23.setObjectName("chb_tbl23")
        self.le_tbl24 = QtWidgets.QLineEdit(self.groupBox_3)
        self.le_tbl24.setGeometry(QtCore.QRect(180, 480, 113, 20))
        self.le_tbl24.setObjectName("le_tbl24")
        self.le_tbl36 = QtWidgets.QLineEdit(self.groupBox_3)
        self.le_tbl36.setGeometry(QtCore.QRect(180, 720, 113, 20))
        self.le_tbl36.setObjectName("le_tbl36")
        self.chb_tbl3 = QtWidgets.QCheckBox(self.groupBox_3)
        self.chb_tbl3.setGeometry(QtCore.QRect(20, 60, 111, 21))
        self.chb_tbl3.setObjectName("chb_tbl3")
        self.pbt_tbl12 = QtWidgets.QPushButton(self.groupBox_3)
        self.pbt_tbl12.setGeometry(QtCore.QRect(310, 240, 75, 23))
        self.pbt_tbl12.setObjectName("pbt_tbl12")
        self.pbt_tbl5 = QtWidgets.QPushButton(self.groupBox_3)
        self.pbt_tbl5.setGeometry(QtCore.QRect(310, 100, 75, 23))
        self.pbt_tbl5.setObjectName("pbt_tbl5")
        self.chb_tbl14 = QtWidgets.QCheckBox(self.groupBox_3)
        self.chb_tbl14.setGeometry(QtCore.QRect(20, 280, 151, 21))
        self.chb_tbl14.setObjectName("chb_tbl14")
        self.chb_tbl10 = QtWidgets.QCheckBox(self.groupBox_3)
        self.chb_tbl10.setGeometry(QtCore.QRect(20, 200, 121, 21))
        self.chb_tbl10.setObjectName("chb_tbl10")
        self.le_tbl15 = QtWidgets.QLineEdit(self.groupBox_3)
        self.le_tbl15.setGeometry(QtCore.QRect(180, 300, 113, 20))
        self.le_tbl15.setObjectName("le_tbl15")
        self.chb_tbl17 = QtWidgets.QCheckBox(self.groupBox_3)
        self.chb_tbl17.setGeometry(QtCore.QRect(20, 340, 81, 17))
        self.chb_tbl17.setObjectName("chb_tbl17")
        self.pbt_tbl35_2 = QtWidgets.QPushButton(self.groupBox_3)
        self.pbt_tbl35_2.setGeometry(QtCore.QRect(310, 700, 75, 23))
        self.pbt_tbl35_2.setObjectName("pbt_tbl35_2")
        self.chb_tbl37 = QtWidgets.QCheckBox(self.groupBox_3)
        self.chb_tbl37.setGeometry(QtCore.QRect(20, 740, 121, 21))
        self.chb_tbl37.setObjectName("chb_tbl37")
        self.le_tbl25 = QtWidgets.QLineEdit(self.groupBox_3)
        self.le_tbl25.setGeometry(QtCore.QRect(180, 500, 113, 20))
        self.le_tbl25.setObjectName("le_tbl25")
        self.chb_tbl26 = QtWidgets.QCheckBox(self.groupBox_3)
        self.chb_tbl26.setGeometry(QtCore.QRect(20, 520, 161, 17))
        self.chb_tbl26.setObjectName("chb_tbl26")
        self.le_tbl5 = QtWidgets.QLineEdit(self.groupBox_3)
        self.le_tbl5.setGeometry(QtCore.QRect(180, 100, 113, 20))
        self.le_tbl5.setObjectName("le_tbl5")
        self.le_tbl22 = QtWidgets.QLineEdit(self.groupBox_3)
        self.le_tbl22.setGeometry(QtCore.QRect(180, 440, 113, 20))
        self.le_tbl22.setObjectName("le_tbl22")
        self.pbt_tbl17 = QtWidgets.QPushButton(self.groupBox_3)
        self.pbt_tbl17.setGeometry(QtCore.QRect(310, 340, 75, 23))
        self.pbt_tbl17.setObjectName("pbt_tbl17")
        self.chb_tbl36 = QtWidgets.QCheckBox(self.groupBox_3)
        self.chb_tbl36.setGeometry(QtCore.QRect(20, 720, 121, 21))
        self.chb_tbl36.setObjectName("chb_tbl36")
        self.chb_tbl7 = QtWidgets.QCheckBox(self.groupBox_3)
        self.chb_tbl7.setGeometry(QtCore.QRect(20, 140, 70, 17))
        self.chb_tbl7.setObjectName("chb_tbl7")
        self.chb_tbl11 = QtWidgets.QCheckBox(self.groupBox_3)
        self.chb_tbl11.setGeometry(QtCore.QRect(20, 220, 131, 21))
        self.chb_tbl11.setObjectName("chb_tbl11")
        self.pbt_tbl13 = QtWidgets.QPushButton(self.groupBox_3)
        self.pbt_tbl13.setGeometry(QtCore.QRect(310, 260, 75, 23))
        self.pbt_tbl13.setObjectName("pbt_tbl13")
        self.chb_tbl13 = QtWidgets.QCheckBox(self.groupBox_3)
        self.chb_tbl13.setGeometry(QtCore.QRect(20, 260, 141, 21))
        self.chb_tbl13.setObjectName("chb_tbl13")
        self.le_tbl8 = QtWidgets.QLineEdit(self.groupBox_3)
        self.le_tbl8.setGeometry(QtCore.QRect(180, 160, 113, 20))
        self.le_tbl8.setObjectName("le_tbl8")
        self.le_tbl16 = QtWidgets.QLineEdit(self.groupBox_3)
        self.le_tbl16.setGeometry(QtCore.QRect(180, 320, 113, 20))
        self.le_tbl16.setObjectName("le_tbl16")
        self.le_tbl34 = QtWidgets.QLineEdit(self.groupBox_3)
        self.le_tbl34.setGeometry(QtCore.QRect(180, 680, 113, 20))
        self.le_tbl34.setObjectName("le_tbl34")
        self.chb_tbl1 = QtWidgets.QCheckBox(self.groupBox_3)
        self.chb_tbl1.setGeometry(QtCore.QRect(20, 20, 91, 21))
        self.chb_tbl1.setObjectName("chb_tbl1")
        self.pbt_tbl9 = QtWidgets.QPushButton(self.groupBox_3)
        self.pbt_tbl9.setGeometry(QtCore.QRect(310, 180, 75, 23))
        self.pbt_tbl9.setObjectName("pbt_tbl9")
        self.le_tbl28 = QtWidgets.QLineEdit(self.groupBox_3)
        self.le_tbl28.setGeometry(QtCore.QRect(180, 560, 113, 20))
        self.le_tbl28.setObjectName("le_tbl28")
        self.chb_tbl34 = QtWidgets.QCheckBox(self.groupBox_3)
        self.chb_tbl34.setGeometry(QtCore.QRect(20, 680, 151, 17))
        self.chb_tbl34.setObjectName("chb_tbl34")
        self.pbt_m4 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pbt_m4.setGeometry(QtCore.QRect(390, 820, 91, 23))
        self.pbt_m4.setObjectName("pbt_m4")
        self.pbt_m1 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pbt_m1.setGeometry(QtCore.QRect(510, 760, 191, 81))
        self.pbt_m1.setObjectName("pbt_m1")
        self.pbt_m3 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pbt_m3.setGeometry(QtCore.QRect(390, 790, 91, 23))
        self.pbt_m3.setObjectName("pbt_m3")
        self.pbt_m2 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pbt_m2.setGeometry(QtCore.QRect(390, 760, 91, 23))
        self.pbt_m2.setObjectName("pbt_m2")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.horizontalLayout.addWidget(self.scrollArea)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.groupBox.setTitle(_translate("Form", "ГРУЗООТПРАВИТЕЛЬ"))
        self.pbt_go2.setText(_translate("Form", "ПОИСК"))
        self.chb_go15.setText(_translate("Form", "Расш. ОКОНХ"))
        self.pbt_go21.setText(_translate("Form", "ПОИСК"))
        self.chb_go7.setText(_translate("Form", "Рынок"))
        self.chb_go4.setText(_translate("Form", "Район"))
        self.chb_go11.setText(_translate("Form", "ОКАТО"))
        self.pbt_go5.setText(_translate("Form", "ПОИСК"))
        self.chb_go14.setText(_translate("Form", "ОКОНХ"))
        self.pbt_go13.setText(_translate("Form", "ПОИСК"))
        self.chb_go17.setText(_translate("Form", "Юр. индекс"))
        self.pbt_go19.setText(_translate("Form", "ПОИСК"))
        self.pbt_go7.setText(_translate("Form", "ПОИСК"))
        self.chb_go9.setText(_translate("Form", "Направл./порт"))
        self.chb_go10.setText(_translate("Form", "Наименование"))
        self.chb_go20.setText(_translate("Form", "Юр. факс"))
        self.pbt_go6.setText(_translate("Form", "ПОИСК"))
        self.chb_go2.setText(_translate("Form", "Станция"))
        self.pbt_go18.setText(_translate("Form", "ПОИСК"))
        self.pbt_go16.setText(_translate("Form", "ПОИСК"))
        self.chb_go16.setText(_translate("Form", "ИНН"))
        self.pbt_go9.setText(_translate("Form", "ПОИСК"))
        self.chb_go13.setText(_translate("Form", "Расш. ОКВЭД"))
        self.chb_go5.setText(_translate("Form", "Ближ. нас. пункт"))
        self.pbt_go15.setText(_translate("Form", "ПОИСК"))
        self.pbt_go3.setText(_translate("Form", "ПОИСК"))
        self.pbt_go11.setText(_translate("Form", "ПОИСК"))
        self.chb_go18.setText(_translate("Form", "Юр. адрес"))
        self.pbt_go12.setText(_translate("Form", "ПОИСК"))
        self.pbt_go4.setText(_translate("Form", "ПОИСК"))
        self.chb_go6.setText(_translate("Form", "Страна"))
        self.pbt_go10.setText(_translate("Form", "ПОИСК"))
        self.pbt_go14.setText(_translate("Form", "ПОИСК"))
        self.chb_go8.setText(_translate("Form", "Категория"))
        self.chb_go12.setText(_translate("Form", "ОКВЭД"))
        self.chb_go21.setText(_translate("Form", "E-mail"))
        self.chb_go19.setText(_translate("Form", "Юр. телефон"))
        self.pbt_go20.setText(_translate("Form", "ПОИСК"))
        self.pbt_go17.setText(_translate("Form", "ПОИСК"))
        self.chb_go1.setText(_translate("Form", "Код станции"))
        self.chb_go3.setText(_translate("Form", "Регион"))
        self.pbt_go8.setText(_translate("Form", "ПОИСК"))
        self.pbt_go1.setText(_translate("Form", "ПОИСК"))
        self.groupBox_2.setTitle(_translate("Form", "ГРУЗОПОЛУЧАТЕЛЬ"))
        self.pbt_gp20.setText(_translate("Form", "ПОИСК"))
        self.pbt_gp19.setText(_translate("Form", "ПОИСК"))
        self.pbt_gp21.setText(_translate("Form", "ПОИСК"))
        self.pbt_gp11.setText(_translate("Form", "ПОИСК"))
        self.pbt_gp6.setText(_translate("Form", "ПОИСК"))
        self.chb_gp19.setText(_translate("Form", "Юр. телефон"))
        self.pbt_gp15.setText(_translate("Form", "ПОИСК"))
        self.pbt_gp8.setText(_translate("Form", "ПОИСК"))
        self.chb_gp9.setText(_translate("Form", "Направл./порт"))
        self.pbt_gp5.setText(_translate("Form", "ПОИСК"))
        self.pbt_gp2.setText(_translate("Form", "ПОИСК"))
        self.chb_gp1.setText(_translate("Form", "Код станции"))
        self.chb_gp17.setText(_translate("Form", "Юр. индекс"))
        self.chb_gp8.setText(_translate("Form", "Категоря"))
        self.chb_gp15.setText(_translate("Form", "Расш. ОКОНХ"))
        self.chb_gp12.setText(_translate("Form", "ОКВЭД"))
        self.pbt_gp9.setText(_translate("Form", "ПОИСК"))
        self.pbt_gp10.setText(_translate("Form", "ПОИСК"))
        self.pbt_gp18.setText(_translate("Form", "ПОИСК"))
        self.chb_gp2.setText(_translate("Form", "Станция"))
        self.pbt_gp3.setText(_translate("Form", "ПОИСК"))
        self.chb_gp4.setText(_translate("Form", "Район"))
        self.chb_gp14.setText(_translate("Form", "ОКОНХ"))
        self.pbt_gp7.setText(_translate("Form", "ПОИСК"))
        self.chb_gp6.setText(_translate("Form", "Страна"))
        self.chb_gp20.setText(_translate("Form", "Юр. факс"))
        self.pbt_gp13.setText(_translate("Form", "ПОИСК"))
        self.pbt_gp12.setText(_translate("Form", "ПОИСК"))
        self.chb_gp7.setText(_translate("Form", "Рынок"))
        self.chb_gp10.setText(_translate("Form", "Наименование"))
        self.pbt_gp4.setText(_translate("Form", "ПОИСК"))
        self.chb_gp21.setText(_translate("Form", "E-mail"))
        self.chb_gp5.setText(_translate("Form", "Ближ. нас. пункт"))
        self.chb_gp18.setText(_translate("Form", "Юр. адрес"))
        self.pbt_gp16.setText(_translate("Form", "ПОИСК"))
        self.chb_gp11.setText(_translate("Form", "ОКАТО"))
        self.chb_gp13.setText(_translate("Form", "Расш. ОКВЭД"))
        self.pbt_gp14.setText(_translate("Form", "ПОИСК"))
        self.chb_gp3.setText(_translate("Form", "Регион"))
        self.chb_gp16.setText(_translate("Form", "ИНН"))
        self.pbt_gp1.setText(_translate("Form", "ПОИСК"))
        self.pbt_gp17.setText(_translate("Form", "ПОИСК"))
        self.groupBox_3.setTitle(_translate("Form", "ФОРМА ТАБЛИЦЫ"))
        self.chb_tbl2.setText(_translate("Form", "Клиент"))
        self.chb_tbl18.setText(_translate("Form", "Отчётный месяц"))
        self.chb_tbl28.setText(_translate("Form", "Ст. назнач. загран."))
        self.chb_tbl8.setText(_translate("Form", "Вес груза"))
        self.chb_tbl5.setText(_translate("Form", "Код получателя"))
        self.pbt_tbl20.setText(_translate("Form", "ПОИСК"))
        self.pbt_tbl15.setText(_translate("Form", "ПОИСК"))
        self.pbt_tbl16.setText(_translate("Form", "ПОИСК"))
        self.pbt_tbl4.setText(_translate("Form", "ПОИСК"))
        self.pbt_tbl24.setText(_translate("Form", "ПОИСК"))
        self.chb_tbl15.setText(_translate("Form", "Характер перевозок"))
        self.pbt_tbl21.setText(_translate("Form", "ПОИСК"))
        self.pbt_tbl23.setText(_translate("Form", "ПОИСК"))
        self.pbt_tbl3.setText(_translate("Form", "ПОИСК"))
        self.pbt_tbl32_2.setText(_translate("Form", "ПОИСК"))
        self.pbt_tbl14.setText(_translate("Form", "ПОИСК"))
        self.pbt_tbl7.setText(_translate("Form", "ПОИСК"))
        self.pbt_tbl28.setText(_translate("Form", "ПОИСК"))
        self.chb_tbl16.setText(_translate("Form", "Продукт"))
        self.chb_tbl32.setText(_translate("Form", "Регион назнач. загран"))
        self.pbt_tbl8.setText(_translate("Form", "ПОИСК"))
        self.chb_tbl9.setText(_translate("Form", "Кол-во вагонов"))
        self.pbt_tbl31_2.setText(_translate("Form", "ПОИСК"))
        self.pbt_tbl36.setText(_translate("Form", "ПОИСК"))
        self.chb_tbl27.setText(_translate("Form", "Код ст. назнач. загран."))
        self.chb_tbl31.setText(_translate("Form", "Номер группы продукта"))
        self.pbt_tbl137.setText(_translate("Form", "ПОИСК"))
        self.pbt_tbl22.setText(_translate("Form", "ПОИСК"))
        self.chb_tbl29.setText(_translate("Form", "Страна назначения"))
        self.chb_tbl25.setText(_translate("Form", "Категория отправ. загран."))
        self.chb_tbl21.setText(_translate("Form", "Ст. отправ. загран."))
        self.pbt_tbl27.setText(_translate("Form", "ПОИСК"))
        self.chb_tbl19.setText(_translate("Form", "Год"))
        self.pbt_tbl25.setText(_translate("Form", "ПОИСК"))
        self.pbt_tbl29_2.setText(_translate("Form", "ПОИСК"))
        self.pbt_tbl26.setText(_translate("Form", "ПОИСК"))
        self.pbt_tbl33_2.setText(_translate("Form", "ПОИСК"))
        self.chb_tbl30.setText(_translate("Form", "Страна назначения ЖД"))
        self.pbt_tbl34_2.setText(_translate("Form", "ПОИСК"))
        self.pbt_tbl11.setText(_translate("Form", "ПОИСК"))
        self.chb_tbl4.setText(_translate("Form", "ОКПО отправителя"))
        self.pbt_tbl10.setText(_translate("Form", "ПОИСК"))
        self.pbt_tbl18.setText(_translate("Form", "ПОИСК"))
        self.chb_tbl24.setText(_translate("Form", "Регион отправ. загран."))
        self.pbt_tbl1.setText(_translate("Form", "ПОИСК"))
        self.pbt_tbl2.setText(_translate("Form", "ПОИСК"))
        self.chb_tbl35.setText(_translate("Form", "Тип вагона1"))
        self.pbt_tbl19.setText(_translate("Form", "ПОИСК"))
        self.pbt_tbl6.setText(_translate("Form", "ПОИСК"))
        self.chb_tbl33.setText(_translate("Form", "Категория назнач. загран"))
        self.chb_tbl12.setText(_translate("Form", "Дата отгрузки (месяц)"))
        self.chb_tbl6.setText(_translate("Form", "ОКПО получателя"))
        self.chb_tbl22.setText(_translate("Form", "Страна отправления"))
        self.pbt_tbl30_2.setText(_translate("Form", "ПОИСК"))
        self.chb_tbl20.setText(_translate("Form", "Код ст. отправ. загран."))
        self.chb_tbl23.setText(_translate("Form", "Страна отправления ЖД"))
        self.chb_tbl3.setText(_translate("Form", "Код отправителя"))
        self.pbt_tbl12.setText(_translate("Form", "ПОИСК"))
        self.pbt_tbl5.setText(_translate("Form", "ПОИСК"))
        self.chb_tbl14.setText(_translate("Form", "Дата получения (месяц)"))
        self.chb_tbl10.setText(_translate("Form", "Тонно-километры"))
        self.chb_tbl17.setText(_translate("Form", "Подгруппа"))
        self.pbt_tbl35_2.setText(_translate("Form", "ПОИСК"))
        self.chb_tbl37.setText(_translate("Form", "Тип вагона3"))
        self.chb_tbl26.setText(_translate("Form", "Направл/порт. отп. загран."))
        self.pbt_tbl17.setText(_translate("Form", "ПОИСК"))
        self.chb_tbl36.setText(_translate("Form", "Тип вагона2"))
        self.chb_tbl7.setText(_translate("Form", "Код груза"))
        self.chb_tbl11.setText(_translate("Form", "Дата отгрузки (день)"))
        self.pbt_tbl13.setText(_translate("Form", "ПОИСК"))
        self.chb_tbl13.setText(_translate("Form", "Дата получения (день)"))
        self.chb_tbl1.setText(_translate("Form", "Код клиента"))
        self.pbt_tbl9.setText(_translate("Form", "ПОИСК"))
        self.chb_tbl34.setText(_translate("Form", "Направ/порт назн. загран"))
        self.pbt_m4.setText(_translate("Form", "Память"))
        self.pbt_m1.setText(_translate("Form", "ПОИСК"))
        self.pbt_m3.setText(_translate("Form", "Записать"))
        self.pbt_m2.setText(_translate("Form", "Стереть"))
